#!/bin/bash

# Data-Viz Lesson Plans directory location
DATAVIZ=~/Path/To/Data-Viz/01-Lesson-Plans
CLASSREPO=~/Documents/TEST # I would keep this a test folder to play with and not mess up the class repo

# Check repo changes before doing anything
function gitchecker () {
   cd $DATAVIZ
   echo "Checking for changes to Lesson Plan"
   diffchecker "Lesson Plan"
   cd $CLASSREPO
   diffchecker "Class Repo"
}

function diffchecker () {
   if git diff-index --quiet HEAD -- & spinner $!; then
      # No changes
      echo $1 is up to date
   else
      # Changes
      read -r -p "$1 has changes, pull down changes? [Y/N]" lessonpull
      if [lessonpull == [yY][eE][sS]|[Yy]]; then
      echo Pulling $1
      git pull -q origin master & spinner $!
      else
      echo Closing Class Helper
      fi
   fi
}


function spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}


function topicfind () {
   # Topic prompt
   read -r -p "What's the topic this week?: " topic        
   topicpath="`find -L $DATAVIZ -maxdepth 1 -iname *$topic* -type d -print`" 
   # Handler for find errors
   if test -z "$topicpath"; then
      echo "$topic lesson not found, try again"
   else
      # Output directory name and confirm prompt
      read -r -p "$(echo $(basename $topicpath))? [Y/N] " input 
   fi
}

function saveyourself () {
   cd $CLASSREPO
   cd $(basename $topicpath)
   echo Cleaning up
   rm -r -f readme.md VideoGuide.md Supplemental
   for x in 1 2 3
      do
      :
      rm $x/TimeTracker.xlsx $x/LessonPlan.md
      done
   echo Creating lesson level .gitignore
   find 1 2 3 -maxdepth 3 -type d | sort | grep -v \"un\|Reg\" > .gitignore
}

function copy2class () {
   # Copy Lesson Plan to class repository
   cp -r $topicpath $CLASSREPO
}


###############################
# Execution Start
###############################

gitchecker
topicfind

case $input in
    [yY][eE][sS]|[Yy])
   echo "Copying $(basename $topicpath) directory to $CLASSREPO"
   copy2class
   saveyourself
 ;;
    [nN][oO]|[Nn])
 echo "No"
       ;;
    *)
 topicfind
 ;;
esac